### PR TITLE
Update maintainer, fix typo in README

### PR DESCRIPTION
**Pull request by bencomp**
**JIRA Ticket**: n/a

# What does this Pull Request do?

Change the maintainer to Jared Whiklo and fix reference to ImageMagick (with *k*).

# What's new?

Jared Whiklo is the new maintainer. ImageMagick is spelled with a k at the end.

# How should this be tested?

n/a

# Additional Notes:

(C)CLA is in place.

# Interested parties

Previous maintainer: @qadan ; new maintainer: @whikloj

### CODE REVIEW

**Review by DiegoPino — APPROVED** [review]
Nice catch!

**Comment by bencomp** [comment]
@DiegoPino thanks. How exactly did you merge this? My original commit 254b29b is not in the branch, so I cannot fast-forward anymore.

**Comment by DiegoPino** [comment]
@bencomp sorry, when i "Squash merge" (which is our standard way or merging), github creates a new Hash for the Pull request, joining all individial commits from your pull request branch into a single one. 
Your original commit inside pull 86 is 
https://github.com/Islandora/islandora_ocr/pull/86/commits/254b29bc1b17e88d8d141d2fcb20980c7caccb66
When merged it becomes 
https://github.com/Islandora/islandora_ocr/commit/89235ef0b501bca03b95fe90992734e2b0c27dd1
(look at the description here) https://github.com/Islandora/islandora_ocr/commits/7.x

Let me help you with your workflow, there are little things that you can do to make it simpler to sync

  1. In your fork, start with a clean bencomp/7.x that is 100% idem to Islandora:7.x 
  2. Instead of making the changes in your bencomp/7.x branch, make a new branch named bencomp/7.x-patch or any other name, 7.x-audit, etc
  3. Apply your changes to that new banch
  4. Make the pull request from that branch. I will squash and merge that pull. 
  5. You can then delete that local branch
  6. [Then sync back your bencomp/7.x](https://help.github.com/articles/syncing-a-fork/) so its 100% identical to Islandora:7.x  again (which brings your recent commit, with that new hash into your fork
  7. keep on doing the same starting from 2 until you are done 

Let me know if that helps.

The reason behind of "squash merging" is logical. Your pull request is actually more than just a copy of one of your commits. Its the whole difference between your pull/local branch and this one + me merging and you coding and all goes into in a different time than your individual coding. In a single pull, multiple commits could be happening and many of them could be trial and errors, so squashing brings all together under a single commit with a new hash.

**Comment by bencomp** [comment]
@DiegoPino thanks very much, this explains it perfectly! I managed to keep everything in one commit, so squashing shouldn't be necessary, but if that's the default way of merging I understand.

I'll start with a new branch next time. Did I overlook these workflow tips?

**Comment by DiegoPino** [comment]
@bencomp, thanks. Will make sure to check next time if you only have a single commit and avoid squashing. Still not sure if Github (they are growing so fast and things change) will keep the hash or not, but I will keep that in mind. Not sure if we have that workflow I wrote here, which actually works pretty well, explicitly somewhere (written). @rosiel @dannylamb do you remember?

**Comment by DiegoPino** [comment]
Hey @bencomp! So i tried a pure merge with a @mrmiguez pull here

It adds clutter = an extra second commit but keeps the original hash around
See https://github.com/Islandora/islandora_checksum/commits/7.x
And The original Hash here https://github.com/Islandora/islandora_checksum/pull/58/commits

As you can notice the 7.x tree now includes after @mrmiguez commit a new one, my action of merging ( codeless commit) there, which will help you with fast forwarding maybe, yes, bit still, feels a bit like usesless info on our tree.
So, worklow and squash merging still feels a better choice and cleaner.

We all learned today 🎈

**Comment by willtp87** [comment]
@DiegoPino I do not think that is official workflow.  And I don't think it should be.  There are many cases where it simply hides useful history. I think it should be left to the discretion of whomever is merging.

**Comment by DiegoPino** [comment]
@willtp87 maybe i miss explained myself, well, a lot is undocumented of course, and as almost anything in islandora, left to the discretion of whoever is doing something applies always. But the workflow I mention https://github.com/Islandora/islandora_ocr/pull/86#issuecomment-375686052 here is the new-branch stuff, pull from there (the numbered list) About squashing I said == "which is our standard way or merging", not an official way of doing, anything out of our standard (release manager standard) is allowed too of course. Let me know if its an issue and i need to change my wording somewhere here, thanks!

**Comment by rosiel** [comment]
The "squash and merge" hasn't really been made our "official way of doing things" but it's a good idea, and some of us have been using it more than others. 

I tried to write out the issue-branch-pull-request workflow, but it never got officially approved. Then a year later, I did the same thing. YMMV, let me know which you like best:
(2017) https://github.com/Islandora/islandora/wiki/Islandora-Pull-Request-Instructions
(2016) https://github.com/Islandora/islandora/wiki/Git-Workflow-Suggestions/a3440e8cc3401100b679c39e3f7b4e1e2d1485e1

**Comment by DiegoPino** [comment]
@rosiel looks like I like the 2017 version a lot. Have to read it fully when on my computer and follow the steps but it reads quite good. Can you remind me what happened to that? did we(not you, we the rest) simply neglect to contribute and to comment?

**Comment by rosiel** [comment]
Yeah, should I post it to the list for approval, or bring it up on the next Committers/Release call?

**Pull request merged**
