### PR TITLE
islandora-1474 - OCR difficulties

### PR DESCRIPTION
**Pull request by ajstanley**
**JIRA Ticket**:[ (Islandora-1474)](https://jira.duraspace.org/browse/ISLANDORA-1474?jql=text%20~%20ocr%20ORDER%20BY%20assignee%20ASC)
# What does this Pull Request do?

TIFFS with embedded alpha layers would fail HOCR.  Now we test for, and remove the alpha layer if present
# What's new?

The alpha layer is tested with $identify -format \"%A\" $file"
If Alpha is present the command returns a <string> of 'True'
if 'True' is returned the image is converted with ImageMagick to something Leptonica finds palatable. 
# How should this be tested?

Add a page object from a tiff with an Alpha layer,  OCR and HOCR should be generated
# Additional Notes:

This code will work on original ingestion or on recreation of derivatives.
# Interested parties

@Islandora/7-x-1-x-committers

### CODE REVIEW

**Comment by DonRichards** [comment]
I'm checking this now. I'll get back when I've completed.

**Comment by DonRichards** [comment]
To be clear the intentions of this is is to remove alpha channel during the processing but not to make any appreciable change to the original object (tif)?

**Comment by agile-humanities** [comment]
Exactly right, Don.  The original asset remains untouched.

**Comment by DonRichards** [comment]
I believe this failed to work....
I did a recording of my methodology in case I missed a step. 
The setup is a 4 page book. First page was the Tiff provided in the Jira ticket and the other 3 are  news paper pages. The news paper Tiffs I use regularly for testing for the book and news paper modules. https://youtu.be/_ki83rXYF5Y
Not Edited so it's 8 minutes but briefly annotated

**Comment by DonRichards** [comment]
Was this tested on Islandora_vagrant? What version of Tesseract?

**Comment by DonRichards** [comment]
@ajstanley So is there any progress on this? Were you able to replicate my results or did you have something different?

**Comment by ajstanley** [comment]
Sorry Don, this fell off my radar (crazy busy here of late).  I moved the
filtering logic a little deeper into the call stack so it gets called
called of zip files as well as singletons.

~Alan

On Wed, Jun 8, 2016 at 2:50 PM, Don Richards notifications@github.com
wrote:

> @ajstanley https://github.com/ajstanley So is there any progress on
> this? Were you able to replicate my results or did you have something
> different?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/Islandora/islandora_ocr/pull/71#issuecomment-224673246,
> or mute the thread
> https://github.com/notifications/unsubscribe/AAeNJxK0xpVabSEzxbcun9GjDpJ3tDYbks5qJwD1gaJpZM4ISDDl
> .

## 

Alan Stanley
Lead Developer and Training Specialist
Agile Humanities

**Comment by DonRichards** [comment]
OK, I'll test it today.

**Comment by DonRichards** [comment]
Good stuff. Works as expected.

**Comment by DonRichards** [comment]
@qadan I believe this is ready to be accepted

**Pull request merged**
