### PR TITLE
Language names extensible

### PR DESCRIPTION
**Pull request by megwill4268**
Suggestion changing language names to be more extensible. Also changing portuguese to be spelled correctly.

### CODE REVIEW

**Comment by d-r-p** [comment]
Thank you, @megwill4268, for your contribution!

Four things, though:
1. I am not entirely sure that I understood what you want to achieve here. I think, the proper way of making the list of languages customisable by users would be through [a hook](https://api.drupal.org/api/drupal/includes%21module.inc/group/hooks/7.x) and an api file. Otherwise, users would still have to touch the core code, no? Or did I miss something?
    In case this is the route you want to take, I could give you a hand, if needed
2. Our continuous integration tool Travis is [complaining about your code](https://travis-ci.org/Islandora/islandora_ocr/jobs/422763646#L669):
    > sites/all/modules/islandora_ocr/includes/language_names.inc:
     +1: [minor] No PHP code was found in this file and short open tags are not allowed by this install of PHP. This file may be using short open tags but PHP does not allow them.

    Indeed, it is always a good idea to watch your submitted code for TravisCI failures
3. I think this is your first contribution to Islandora, so you will need to sign a [Contributor License Agreement](https://github.com/Islandora/islandora/wiki/Contributor-License-Agreements) before this can be merged
4. We usually track issues (or improvement request) on [JIRA](https://jira.duraspace.org/projects/ISLANDORA/issues). Would you be willing to register there and open a ticket for this?

**Comment by megwill4268** [comment]
@d-r-p thank you. I am new to islandora/php and was trying to get a feel for what you thought on the idea before I fully implemented it. Is there another forum/ way to initiate that conversation I should use?

**Comment by d-r-p** [comment]
@megwill4268 Contributions (or discussions about the possibility thereof) are always welcome.

As outlined in [`CONTRIBUTING.md`](https://github.com/Islandora/islandora_ocr/blob/7.x/CONTRIBUTING.md), the Islandora community has some workflows in place in order to efficiently track bugs or feature requests and foster the discussion about their resolution or implementation (and, of course, to ensure transparency, traceability and quality).
In order to just get some feedback on certain (even preliminary) ideas, a less formal way to get in touch are the two mailing lists for [users](https://groups.google.com/group/islandora) and [developers](https://groups.google.com/group/islandora-dev).
Even less formally, an easy way to ask questions is in the `#islandora` irc channel on [freenode](https://webchat.freenode.net/).
(See also Islandora's [community page](https://islandora.ca/community).)

If you need the set of languages for tesseract to be user configurable, you might want to submit a feature request ticket in [JIRA](https://jira.duraspace.org/projects/ISLANDORA/issues). If you wish to take the burden, state that you will be providing an implementation, perhaps asking for opinions about the best way of doing so. Alternatively, let the community worry about making it happen (but that depends on how much of a rush you are in).
If you are just interested in knowing how many installations would welcome the feature, then you could send an email to the mailing list.

I hope this helps. Please let me know if I can be of further assistance.

**Comment by whikloj** [comment]
@megwill4268 before you close this out I was thinking that while the larger discussion of extending the available languages can occur separately and this PR could be re-focused to handle those spelling errors 🤷‍♂️ It would be a useful fix. But it would require you to have signed a CLA as @d-r-p mentioned above. Then you could (or if it helps I can) create a simple JIRA ticket for the work.

**Comment by d-r-p** [comment]
:+1: @whikloj

Perhaps we could even include Latin (and other languages supported by tesseract?) while we are at it?

@megwill4268 Would you like to sign a CLA, re-open this PR and push a commit to your `language_names_extensible` branch that reverts the changes so far, but mends `$language_names` in `islandora_ocr_tesseract_language_name()` in `includes/utilities.inc`?

**Comment by whikloj** [comment]
@megwill4268 you can also take this discussion to the mailing list (https://groups.google.com/forum/#!forum/islandora) or we can open a [new JIRA ticket](https://jira.duraspace.org/projects/ISLANDORA/issues) and have the discussion there.

I think there is value to what you are proposing and previous work you can copy/build from and we'd be happy to help you however we can.

**Pull request closed without merging**
