### PR TITLE
Adding escaped quotes surrounding term

### PR DESCRIPTION
**Pull request by IAMlKeno**
**ISLANDORA-2518**: (https://jira.lyrasis.org/browse/ISLANDORA-2518)

# What does this Pull Request do?
It appears that search terms such as those with certain apostrophes can lead to xpath warnings.
This solves the warnings produced: "Invalid predicate in HOCR->findTermNodes()" and "Invalid expression in HOCR->findTermNodes()"

# How should this be tested?

A description of what steps someone could take to:
* Add the file attached to the JIRA ticket as the HOCR datastream of a page object.
* Navigate to the object and add the following url params:
```
?solr[query]=bird's eye&solr[params][defType]=dismax&solr[params][sort]=score desc&solr[params][facet]=true&solr[params][facet.mincount]=1&solr[params][facet.limit]=100&solr[params][facet.field][1]=mods_genre_ms&solr[params][facet.field][2]=mods_relatedItem_host_titleInfo_title_ms&solr[params][facet.field][3]=mods_subject_topic_ms&solr[params][facet.field][4]=mods_subject_name_personal_namePart_ms&solr[params][facet.date][0]=mods_originInfo_dateIssued_mdt&solr[params][f.mods_originInfo_dateIssued_mdt.facet.date.start]=NOW/YEAR-200YEARS&solr[params][f.mods_originInfo_dateIssued_mdt.facet.date.end]=NOW&solr[params][f.mods_originInfo_dateIssued_mdt.facet.date.gap]=%2B1YEAR&solr[params][facet.date.start]=NOW/YEAR-20YEARS&solr[params][facet.date.end]=NOW&solr[params][facet.date.gap]=%2B1YEAR&solr[params][f.mods_originInfo_dateIssued_mdt.facet.mincount]=0&solr[params][fq][0]=-RELS_EXT_isConstituentOf_uri_mt%3A[* TO *]&solr[params][fq][1]=RELS_EXT_isViewableByUser_literal_ms%3A"anonymous" OR RELS_EXT_isViewableByRole_literal_ms%3A"anonymous user" OR ((*%3A* -RELS_EXT_isViewableByUser_literal_ms%3A[* TO *]) AND (*%3A* -RELS_EXT_isViewableByRole_literal_ms%3A[* TO *]))
```
* The object should load appropriately with various highlighting in place.

# Interested parties
* @Natkeeran 
* @Islandora/7-x-1-x-committers

### CODE REVIEW

**Comment by IAMlKeno** [comment]
Hello, any feedback on this pull request?
@Natkeeran

**Comment by nhart** [comment]
Hello @Islandora/7-x-1-x-committers, is there a chance someone can review this PR?

**Comment by DiegoPino** [comment]
@nhart I can later today! Will let you know.

**Comment by DiegoPino** [comment]
Hey. So I looked at the code and the solution is the most accepted one around the wide (and long) internet (e.g [here](https://stackoverflow.com/questions/1341847/special-character-in-xpath-query) when you can't compile the XPath expression which is what we get in PHP). So code/new functions check and I'm ok but... DCS are failing because 
https://github.com/Islandora/islandora_ocr/blob/a4daa48f19123168632920058a9ca3fb0c831e94/includes/utilities.inc#L111
there is a comma missing in that last array item (perfectly good PHP, bad Drupal CS)

Could anyone (since you are here) push a tiny comma there so we have this green?  I will approve in the meantime (since I know you will) and merge in 24 hours. Thanks!

**Review by DiegoPino — APPROVED** [review]
Approving because logic checks (good). Will wait for some committer @IAMlKeno ? to push a comma into that utilities.inc file (line 111) so we have a green. Please do not merge before! Thanks

**Comment by IAMlKeno** [comment]
@DiegoPino seems there's a bit more going on than the comma. I'm at a loss for pertaining to the ci failure

**Comment by DiegoPino** [comment]
Hi @IAMlKeno its the same `array` now complaining about indentation, should be 4 spaces, has 6. Can you run `phpcs` on that file locally? Sadly travis will expose more errors as you get one fixed. Pretty sure its just that utilities.inc file. Good night

**Comment by IAMlKeno** [comment]
Thanks for the help @DiegoPino. We seem greenlit now

**Comment by DiegoPino** [comment]
@IAMlKeno great. 9 hours to go and I merge. Good work here!

**Comment by nhart** [comment]
Hi @DiegoPino, mind pushing that merge button so we can get this deployed? Please? :)

**Comment by DiegoPino** [comment]
Done! Sorry, got distracted. Will mark the jira ticket as solved in a few. Thx

**Comment by nhart** [comment]
No problem! Thank you for taking the time to review and merge.

Cheers!

**Pull request merged**
