### PR TITLE
Change url to solr transformation in README.md

### PR DESCRIPTION
**Pull request by zuphilip**
This transformation is now part of the included submodule, cf.
https://github.com/discoverygarden/basic-solr-config/commit/d268fdfa69b9157cc2cfd2fbdf29bac976c38b19

### CODE REVIEW

**Review by DiegoPino — APPROVED** [review]
Cool. Thanks!

**Comment by DiegoPino** [comment]
@manez do we have a [CLA in file](https://github.com/Islandora/islandora/wiki/Contributor-License-Agreements) 😄 for @zuphilip? Once that is solved, we can merge @zuphilip. Thanks a lot.

**Comment by manez** [comment]
@DiegoPino @zuphilip we will need a signed Contributor License Agreement to get this merged. You can find details (and the forms) [here](https://github.com/Islandora/islandora/wiki/Contributor-License-Agreements). Thank you!

**Comment by zuphilip** [comment]
I am sorry, but this English contract text CLA is too hard to understand for me as I am neither a laywer nor is my mother tongue English. 

However, this PR can be looked at as CC0/PublicDomain. It just replacing a link. Feel free to merge it, copy it, redo it, or whatever is best possible for you.

**Comment by manez** [comment]
@zuphilip the substance of our CLA is to guarantee that any code contributed to Islandora is given to us with the right to release it open source, while also affirming that the contributor (you) does not give up any rights to use the code for your own purposes. However, I can understand if you prefer not to take my word for that.

Our policies require a CLA for any merge, but I will take the issue to our [Roadmap Committee](https://github.com/Islandora/islandora/wiki/Roadmap-Committee-Terms-of-Reference) this week for discussion about whether we can accept a contribution as CC0.

**Comment by manez** [comment]
@zuphilip unfortunately, we determined that we can't make an exception to our policies regarding CLAs for contributions. Thank you for making this change available for someone to redo so that it can go in anyway. @DiegoPino has a signed CLA and a new pull request #83 to resolve the issue.

Thank you very much for your contribution to our project.

**Pull request closed without merging**
